### ISSUE TITLE
Terraria

### ISSUE THREAD

**Issue by Ububewebeb** [skyline-emu/skyline-games-list#737] opened 2022-06-28 22:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1205

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.google.com/amp/s/m.gsmarena.com/xiaomi_poco_f3-ampp-10758.php

### Game Behaviour

Crashes after first loading screen
![Screenshot_2022-06-29-06-44-11-113_skyline emu](https://user-images.githubusercontent.com/103633528/176316832-1206cc28-5689-4796-9814-e6a48dde12bc.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.sklog.zip](https://github.com/skyline-emu/skyline-games-list/files/9005890/emulation.sklog.zip)

**Comment by Crytonics** [comment] 2022-06-28 22:47
Duplicate of #10

**Closed by Crytonics** 2022-06-28 22:47 UTC

**Comment by Crytonics** [comment] 2022-06-28 22:49
You can comment in https://github.com/skyline-emu/skyline-games-list/issues/10 if you have update for that game
