### ISSUE TITLE
Neptunia x SENRAN KAGURA: Ninja Wars

### ISSUE THREAD

**Issue by Unknownzombie01** [skyline-emu/skyline-games-list#1323] opened 2022-12-22 12:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge-v19

### Android Version

13

### SoC type

Snapdragon

### Device GSMArena link

https://www.google.com/amp/s/m.gsmarena.com/samsung_galaxy_s20-ampp-10081.php

### Game Behaviour

Game runs perfectly fine after a few boots it will glitch and freeze if u don't use v12 turnip drivers but after you play for around 20 mins you will notice the framedrops dissapear and the game runs smoorh

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

I

**Comment by Crytonics** [comment] 2022-12-25 14:46
Duplicate of  #1072

**Closed by Crytonics** 2022-12-25 14:46 UTC
