### ISSUE TITLE
A.O.T. 2

### ISSUE THREAD

**Issue by ghost** [skyline-emu/skyline-games-list#27] opened 2022-04-26 17:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1167

### Android Version

11

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_x3_pro-ampp-10802.php

### Game Behaviour

-sound present but really annoying (pzzzz)
-freeze after first 3d model appearance(building roof)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

log and gameplay
https://mega.nz/folder/EhFwiYJL#VvJHCCSHS-FyXHI40SF4qA
```
E19909GPFIFORun: Signal: Segmentation fault @ 0x10 (PC: 0x73ACA86C70)
Stack Trace:
* 0x73ACA86C70 (from libskyline.so)
* 0x73ACAB24C8 (skyline::gpu::interconnect::CommandExecutor::Execute() from libskyline.so)
* 0x73ACAC70DC (skyline::soc::gm20b::engine::maxwell3d::Maxwell3D::HandleMethod(unsigned int, unsigned int) from libskyline.so)
* 0x73ACABD6CC (skyline::soc::gm20b::ChannelGpfifo::Process(skyline::soc::gm20b::GpEntry) from libskyline.so)
* 0x73ACABD254 (from libskyline.so)
* 0x73ACABC8D0 (skyline::soc::gm20b::ChannelGpfifo::Run() from libskyline.so)
* 0x73ACABD034 (from libskyline.so)
* 0x749E5AF86C (from libc.so)
* 0x749E54FA8C (from libc.so)
E19991HOS-478svcMapMemory: Cannot find memory object in handle table for address 0x1893FD6000
Stack Trace:
* 0x73ACA51E34 (skyline::kernel::svc::MapMemory(skyline::DeviceState const&) from libskyline.so)
* 0x73ACA3DA14 (skyline::nce::NCE::SvcHandler(unsigned short, skyline::nce::ThreadContext*) from libskyline.so)
* 0x802E310B8 (from sdk.nso.patch)
* 0x802EBD5D4 (nn::os::detail::ThreadManager::CreateAliasStackUnsafe(nn::os::ThreadType*) from sdk.nso)
* 0x802EBD724 (nn::os::detail::ThreadManager::CreateThread(nn::os::ThreadType*, void (*)(void*), void*, void*, unsigned long, int, int) from sdk.nso)
* 0x802EBD92C (nn::os::detail::ThreadManager::CreateThread(nn::os::ThreadType*, void (*)(void*), void*, void*, unsigned long, int) from sdk.nso)
* 0x802EBBF30 (nn::os::CreateThread(nn::os::ThreadType*, void (*)(void*), void*, void*, unsigned long, int) from sdk.nso)
* 0x803078AF4 (multimedia_ThreadCreate from sdk.nso)
* 0x801A6289C (from subsdk0.nso)
* 0x801A087B0 (NvMMLiteOpenBlock from subsdk0.nso)
* 0x801A3E270 (from subsdk0.nso)
* 0x801A367E0 (from subsdk0.nso)
* 0x801A0F418 (from subsdk0.nso)
* 0x801A0E158 (from subsdk0.nso)
* 0x801A17E80 (from subsdk0.nso)
* 0x802EBD8A8 (from sdk.nso)
* 0x802EC1958 (from sdk.nso)
* 0x802EC18D8 (from sdk.nso)
E19992HOS-7Signal: Segmentation fault @ 0x20 (PC: 0x73ACA5C8B8) (SVC: SvcWaitSynchronization)
Stack Trace:
* 0x73ACA5C8B8 (skyline::kernel::svc::WaitSynchronization(skyline::DeviceState const&) from libskyline.so)
* 0x73ACA3DA14 (skyline::nce::NCE::SvcHandler(unsigned short, skyline::nce::ThreadContext*) from libskyline.so)
* 0x802E310B8 (from sdk.nso.patch)
* 0x80074B720 (from main.nso)
* 0x80074B450 (from main.nso)
* 0x8007A4F28 (from main.nso)
* 0x802EBD8A8 (from sdk.nso)
* 0x802EC1958 (from sdk.nso)
* 0x802EC18D8 (from sdk.nso)
* ```

**Comment by Crytonics** [comment] 2023-01-03 20:51
I will close this issue because there is another issue for this game that is updated.
Duplicate of #581

**Closed by Crytonics** 2023-01-03 20:51 UTC
Labels: status-boots, audio, nvdec, kernel
