### ISSUE TITLE
POKEMON MYSTERY DUNGEON RESCUE TEAM DX

### ISSUE THREAD

**Issue by dodoltrash** [skyline-emu/skyline-games-list#1221] opened 2022-11-29 01:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge 15

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_x3_pro-ampp-10802.php

### Game Behaviour

- Trecko and Cyndaquil missing skin
![Screenshot_2022-11-29-07-55-15-359_skyline emu](https://user-images.githubusercontent.com/101286848/204413210-a4cc0ea4-a018-4281-a0a0-f0cfb33830dc.jpg)

![Screenshot_2022-11-29-07-57-12-692_skyline emu](https://user-images.githubusercontent.com/101286848/204413266-59cb2541-b525-416a-913d-2477dd3230fd.jpg)
- Treecko eye missing

![Screenshot_2022-11-29-07-57-43-448_skyline emu](https://user-images.githubusercontent.com/101286848/204413309-90d736a6-6c5f-4015-b4d3-7ae35d8b4972.jpg)
- when move skin disappear

https://user-images.githubusercontent.com/101286848/204414184-1ec98c38-3aff-4a1f-81bb-a1d7aca338d3.mp4

- missing skin

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.txt](https://github.com/skyline-emu/skyline-games-list/files/10108853/emulation.txt)

**Comment by khangabc62** [comment] 2022-11-29 11:47
How download

**Comment by JERD001** [comment] 2022-11-29 12:32
From the eShop on your switch

**Comment by iplaysomegames101** [comment] 2022-11-29 13:15
and have a modded switch

**Comment by EZonTheEyes** [comment] 2022-11-30 07:59
Duplicate of issue #255 please update existing issue in comment

**Closed by EZonTheEyes** 2022-11-30 07:59 UTC
