### ISSUE TITLE
Metroid Dread

### ISSUE THREAD

**Issue by Jo580rn3** [skyline-emu/skyline-games-list#726] opened 2022-06-25 19:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1206

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/samsung_galaxy_z_fold3_5g-10906.php

### Game Behaviour

- No image when game finishes loading
- Sound frizzles at a steady rate
- Game not responding to inputs

https://user-images.githubusercontent.com/14138669/175787950-43e94ea8-94fb-4521-be3f-1a5ba7f2d8ab.mp4

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/8985448/emulation.zip)

**Comment by Crytonics** [comment] 2022-06-25 19:41
Duplicate of #112

**Closed by Crytonics** 2022-06-25 19:41 UTC
