### ISSUE TITLE
Nickelodeon all star brawls 

### ISSUE THREAD

**Issue by Zhafranilhamj** [skyline-emu/skyline-games-list#1332] opened 2022-12-27 05:11 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Tested Build

Skyline 1622

### Android Version

12

### SoC type

Exynos

### Device GSMArena link

https://m.gsmarena.com/samsung_galaxy_note10+-9732.php

### Game Behaviour

Game works fine but when you start the battle game crashes
![Screenshot_20221227-125348](https://user-images.githubusercontent.com/96971729/209614531-b601013b-31ba-45ed-b944-2e952e71aa94.jpg)

https://user-images.githubusercontent.com/96971729/209614999-f65ee798-bb6d-4a9e-a141-8fbe43f5d090.mp4

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[root_logs_emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/10306041/root_logs_emulation.zip)
[root_logs_emulation.sklog.txt](https://github.com/skyline-emu/skyline-games-list/files/10306185/root_logs_emulation.sklog.txt)
I75EmuMainCreateDevice: Vulkan Device: Name: Mali-G76 Type: IntegratedGpu Driver ID: ArmProprietary Vulkan Version: 1.1.177 Driver Version: 32.1.0 Queues: * 2xGCT--: TSB64 MIG(1x1x1) <-- Extensions: * VK_KHR_incremental_present (v0.0.1) * VK_EXT_hdr_metadata (v0.0.2) * VK_KHR_shared_presentable_image (v0.0.1) * VK_GOOGLE_display_timing (v0.0.1) * VK_KHR_16bit_storage (v0.0.1) * VK_KHR_8bit_storage (v0.0.1) * VK_KHR_bind_memory2 (v0.0.1) * VK_KHR_buffer_device_address (v0.0.1) * VK_KHR_create_renderpass2 (v0.0.1) * VK_KHR_dedicated_allocation (v0.0.3) * VK_KHR_depth_stencil_resolve (v0.0.1) * VK_KHR_descriptor_update_template (v0.0.1) * VK_KHR_device_group (v0.0.4) * VK_KHR_driver_properties (v0.0.1) * VK_KHR_external_fence (v0.0.1) * VK_KHR_external_fence_fd (v0.0.1) * VK_KHR_external_memory (v0.0.1) * VK_KHR_external_memory_fd (v0.0.1) * VK_KHR_external_semaphore (v0.0.1) * VK_KHR_external_semaphore_fd (v0.0.1) * VK_KHR_get_memory_requirements2 (v0.0.1) * VK_KHR_image_format_list (v0.0.1) * VK_KHR_imageless_framebuffer (v0.0.1) * VK_KHR_maintenance1 (v0.0.2) * VK_KHR_maintenance2 (v0.0.1) * VK_KHR_maintenance3 (v0.0.1) * VK_KHR_multiview (v0.0.1) * VK_KHR_relaxed_block_layout (v0.0.1) * VK_KHR_sampler_mirror_clamp_to_edge (v0.0.3) * VK_KHR_sampler_ycbcr_conversion (v0.0.14) * VK_KHR_separate_depth_stencil_layouts (v0.0.1) * VK_KHR_shader_draw_parameters (v0.0.1) * VK_KHR_shader_float16_int8 (v0.0.1) * VK_KHR_shader_float_controls (v0.0.4) * VK_KHR_shader_non_semantic_info (v0.0.1) * VK_KHR_shader_subgroup_extended_types (v0.0.1) * VK_KHR_spirv_1_4 (v0.0.1) * VK_KHR_storage_buffer_storage_class (v0.0.1) * VK_KHR_timeline_semaphore (v0.0.2) * VK_KHR_uniform_buffer_standard_layout (v0.0.1) * VK_KHR_variable_pointers (v0.0.1) * VK_KHR_vulkan_memory_model (v0.0.3) * VK_EXT_astc_decode_mode (v0.0.1) * VK_EXT_calibrated_timestamps (v0.0.2) * VK_EXT_global_priority (v0.0.2) * VK_EXT_host_query_reset (v0.0.1) * VK_EXT_image_robustness (v0.0.1) * VK_EXT_index_type_uint8 (v0.0.1) * VK_EXT_inline_uniform_block (v0.0.1) * VK_EXT_line_rasterization (v0.0.1) * VK_EXT_provoking_vertex (v0.0.1) * VK_EXT_queue_family_foreign (v0.0.1) * VK_EXT_device_memory_report (v0.0.2) * VK_EXT_scalar_block_layout (v0.0.1) * VK_EXT_separate_stencil_usage (v0.0.1) * VK_EXT_subgroup_size_control (v0.0.2) * VK_EXT_texture_compression_astc_hdr (v0.0.1) * VK_EXT_shader_subgroup_ballot (v0.0.1) * VK_EXT_shader_subgroup_vote (v0.0.1) * VK_EXT_transform_feedback (v0.0.1) * VK_EXT_external_memory_dma_buf (v0.0.1) * VK_EXT_image_drm_format_modifier (v0.0.1) * VK_EXT_custom_border_color (v0.0.12) * VK_ANDROID_external_memory_android_hardware_buffer (v0.0.3) * VK_KHR_swapchain (v0.0.70) * VK_EXT_4444_formats (v0.0.1) Traits: * Supports U8 Indices: true * Supports Sampler Mirror Clamp To Edge: false * Supports Sampler Reduction Mode: false * Supports Custom Border Color (Without Format): true * Supports Anisotropic Filtering: true * Supports Last Provoking Vertex: true * Supports Logical Operations: false * Supports Vertex Attribute Divisor: false * Supports Vertex Attribute Zero Divisor: false * Supports Push Descriptors: false * Supports Imageless Framebuffers: true * Supports Global Priority: true * Supports Multiple Viewports: false * Supports Shader Viewport Index: false * Supports SPIR-V 1.4: true * Supports Shader Invocation Demotion: false * Supports 16-bit FP: true * Supports 8-bit Integers: true * Supports 16-bit Integers: true * Supports 64-bit Integers: false * Supports Atomic 64-bit Integers: false * Supports Floating Point Behavior Control: true * Supports Image Read Without Format: true * Supports List Primitive Topology Restart: false * Supports Patch List Primitive Topology Restart: false * Supports Transform Feedback: false * Supports Geometry Shaders: true * Supports Vertex Pipeline Stores and Atomics: false * Supports Fragment Stores and Atomics: true * Supports Shader Storage Image Write Without Format: true *Supports Subgroup Vote: true * Subgroup Size: 8 * BCn Support: 0000000 Quirks: * Needs Individual Texture Binding Writes: false * VkImage Mutable Format is costly: false * Adreno Relaxed Format Aliasing: false * Adreno Broken Format Reporting: false * Broken Descriptor Aliasing: false * Relaxed Render Pass Compatibility: false * Max Subpass Count: 4294967295 * Max Global Queue Priority: High D304EmuMainShader Compiler (Shader_SPIRV): Fp32 denorm flush and preserve on the same shader D305EmuMainShader Compiler (Shader_SPIRV): Fp32 denorm flush and preserve on the same shader W305EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support W305EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support D306EmuMainShader Compiler (Shader_SPIRV): Fp32 denorm flush and preserve on the same shader W306EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support W307EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support W308EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support D310EmuMainShader Compiler (Shader_SPIRV): Fp32 denorm flush and preserve on the same shader W310EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support W310EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support W312EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support D314EmuMainShader Compiler (Shader_SPIRV): Fp32 denorm flush and preserve on the same shader W314EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support W316EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support W317EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support W318EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support W319EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support W321EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support D325EmuMainShader Compiler (Shader_SPIRV): Fp32 denorm flush and preserve on the same shader W325EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support W328EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support D330EmuMainShader Compiler (Shader_SPIRV): Fp32 denorm flush and preserve on the same shader W330EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support D332EmuMainShader Compiler (Shader_SPIRV): Fp32 denorm flush and preserve on the same shader W332EmuMainMakeCompiledPipeline: Depth clamp used on guest without host support I332EmuMainPipelineManager: Loaded 18 graphics pipelines in 28ms I332EmuMainNPDM Metadata: Title: ID: 100DCF013740000, Version: 0 Main Thread: Priority: 44, Stack Size: 0x100000 Scheduler: Ideal Core: 0, Core Mask: 0111, Priority: 28 - 59 Kernel Version: v9.1 I342EmuMainLoadExeFs: Loaded 'rtld.nso' at 0x800000000 (.text @ 0x800001000) I855EmuMainLoadExeFs: Loaded 'main.nso' at 0x800005000 (.text @ 0x800007000) I896EmuMainLoadExeFs: Loaded 'subsdk0.nso' at 0x804665000 (.text @ 0x804667000) I982EmuMainLoadExeFs: Loaded 'sdk.nso' at 0x804D0D000 (.text @ 0x804D10000) I982EmuMainStarting "Nickelodeon All-Star Brawl" (0100DCF013740000) v1.0.0 by "GameMill Entertainment" I982EmuMainExecute: Starting main HOS thread

**Comment by Crytonics** [comment] 2022-12-27 16:18
Duplicate of #824

**Closed by Crytonics** 2022-12-27 16:18 UTC
