### ISSUE TITLE
<Pokemon Legends Arceus>

### ISSUE THREAD

**Issue by NotAvailable23** [skyline-emu/skyline-games-list#1359] opened 2023-01-10 10:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1706

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.google.com/amp/s/m.gsmarena.com/vivo_v20_pro-ampp-10462.php

### Game Behaviour

"- Cannot get past character creation and the (game freezes) and in version 1632, you character creation is completed but the game world and tutorial never begin. The game used to freeze when the screen went black(it was supposed to) but now you can't get past the dialogue after character creation- " 

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/10381496/emulation.zip)
#1359 Pokemon Legends: Arceus

**Comment by MuhSlam** [comment] 2023-01-10 10:47
This game already have on the list 
Duplicate of #247

**Closed** 2023-01-10 16:17 UTC
