### ISSUE TITLE
The Flame in the Flood: Complete Edition

### ISSUE THREAD

**Issue by GoldenBurnik** [skyline-emu/skyline-games-list#906] opened 2022-08-08 14:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1295

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_mi_9t_pro-ampp-9791.php

### Game Behaviour

Crashes on startup, no screeshot, returning to menu when starting up

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[flamesde.txt](https://github.com/skyline-emu/skyline-games-list/files/9282614/flamesde.txt)

**Comment by Crytonics** [comment] 2022-08-08 19:04
Duplicate of #593

**Closed by Crytonics** 2022-08-08 19:04 UTC
