### ISSUE TITLE
Crysis remastered 

### ISSUE THREAD

**Issue by Bgf12** [skyline-emu/skyline-games-list#1478] opened 2023-03-09 11:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

2074

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/motorola_edge_x30-11262.php

### Game Behaviour

The game works fine but there are a lot of graphical glitches! There is close to no graphics

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[Log](https://drive.google.com/file/d/14se98ZyMxcgZrmkPPOPuI4DjXghDZsff/view?usp=drivesdk)

**Comment by MuhSlam** [comment] 2023-03-09 11:07
Duplicate of #235
Use search tool next time

**Comment by EZonTheEyes** [comment] 2023-03-12 14:57
Duplicate of #235 please submit updated information as a comment there

**Closed by EZonTheEyes** 2023-03-12 14:57 UTC
