### ISSUE TITLE
Hyper Light Drifter

### ISSUE THREAD

**Issue by sadaqali2** [skyline-emu/skyline-games-list#676] opened 2022-06-18 16:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1200

### Android Version

11

### SoC type

Mediatek

### Device GSMArena link

https://www.google.com/amp/s/m.gsmarena.com/oneplus_nord_2_5g-ampp-10960.php

### Game Behaviour

-Black Screen when starting game
-Game doesn't even start
![Screenshot_2022-06-18-19-13-46-40_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/107765667/174447989-ba20ae0d-72a4-45c2-923e-1fb5828fac40.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[HLD.zip](https://github.com/skyline-emu/skyline-games-list/files/8933965/HLD.zip)

**Comment by Crytonics** [comment] 2022-06-18 16:33
Duplicate of #38

**Closed by Crytonics** 2022-06-18 16:33 UTC
