### ISSUE TITLE
Diablo III: Eternal Collection

### ISSUE THREAD

**Issue by GoldenBurnik** [skyline-emu/skyline-games-list#905] opened 2022-08-08 14:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1295

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_mi_9t_pro-ampp-9791.php

### Game Behaviour

Black screen freeze on startup, then crash
![Screenshot_20220808-222324_Skyline](https://user-images.githubusercontent.com/110814965/183441935-780197fe-7f1d-4ea7-bd6f-933782172919.png)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[diablorks.txt](https://github.com/skyline-emu/skyline-games-list/files/9282552/diablorks.txt)

**Comment by Crytonics** [comment] 2022-08-08 19:03
Duplicate of #585

**Closed by Crytonics** 2022-08-08 19:03 UTC
