### ISSUE TITLE
Pokemon Lets go Pikachu

### ISSUE THREAD

**Issue by NihalPadwal** [skyline-emu/skyline-games-list#1103] opened 2022-09-25 17:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Latest

### Android Version

11

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/oneplus_nord-10289.php

### Game Behaviour

Just black screen 

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

I21EmuMainCreateDevice: Vulkan Device:
Name: Turnip Adreno (TM) 620
Type: IntegratedGpu
Driver ID: MesaTurnip
Vulkan Version: 1.3.228
Driver Version: 22.2.99
Queues:
* 1xGCT--: TSB48 MIG(1x1x1) <--
Extensions:
* VK_KHR_incremental_present (v0.0.1)
* VK_EXT_hdr_metadata (v0.0.2)
* VK_GOOGLE_display_timing (v0.0.1)
* VK_KHR_bind_memory2 (v0.0.1)
* VK_KHR_buffer_device_address (v0.0.1)
* VK_KHR_copy_commands2 (v0.0.1)
* VK_KHR_create_renderpass2 (v0.0.1)
* VK_KHR_dedicated_allocation (v0.0.3)
* VK_KHR_depth_stencil_resolve (v0.0.1)
* VK_KHR_descriptor_update_template (v0.0.1)
* VK_KHR_device_group (v0.0.4)
* VK_KHR_draw_indirect_count (v0.0.1)
* VK_KHR_driver_properties (v0.0.1)
* VK_KHR_external_fence (v0.0.1)
* VK_KHR_external_fence_fd (v0.0.1)
* VK_KHR_external_memory (v0.0.1)
* VK_KHR_external_memory_fd (v0.0.1)
* VK_KHR_external_semaphore (v0.0.1)
* VK_KHR_external_semaphore_fd (v0.0.1)
* VK_KHR_get_memory_requirements2 (v0.0.1)
* VK_KHR_image_format_list (v0.0.1)
* VK_KHR_imageless_framebuffer (v0.0.1)
* VK_KHR_maintenance1 (v0.0.2)
* VK_KHR_maintenance2 (v0.0.1)
* VK_KHR_maintenance3 (v0.0.1)
* VK_KHR_multiview (v0.0.1)
* VK_KHR_pipeline_executable_properties (v0.0.1)
* VK_KHR_pipeline_library (v0.0.1)
* VK_KHR_push_descriptor (v0.0.2)
* VK_KHR_relaxed_block_layout (v0.0.1)
* VK_KHR_sampler_mirror_clamp_to_edge (v0.0.3)
* VK_KHR_sampler_ycbcr_conversion (v0.0.14)
* VK_KHR_separate_depth_stencil_layouts (v0.0.1)
* VK_KHR_shader_draw_parameters (v0.0.1)
* VK_KHR_shader_float16_int8 (v0.0.1)
* VK_KHR_shader_float_controls (v0.0.4)
* VK_KHR_shader_integer_dot_product (v0.0.1)
* VK_KHR_shader_non_semantic_info (v0.0.1)
* VK_KHR_shader_subgroup_extended_types (v0.0.1)
* VK_KHR_shader_terminate_invocation (v0.0.1)
* VK_KHR_spirv_1_4 (v0.0.1)
* VK_KHR_storage_buffer_storage_class (v0.0.1)
* VK_KHR_synchronization2 (v0.0.1)
* VK_KHR_uniform_buffer_standard_layout (v0.0.1)
* VK_KHR_variable_pointers (v0.0.1)
* VK_KHR_vulkan_memory_model (v0.0.3)
* VK_KHR_zero_initialize_workgroup_memory (v0.0.1)
* VK_EXT_4444_formats (v0.0.1)
* VK_EXT_attachment_feedback_loop_layout (v0.0.2)
* VK_EXT_border_color_swizzle (v0.0.1)
* VK_EXT_color_write_enable (v0.0.1)
* VK_EXT_conditional_rendering (v0.0.2)
* VK_EXT_custom_border_color (v0.0.12)
* VK_EXT_depth_clip_control (v0.0.1)
* VK_EXT_depth_clip_enable (v0.0.1)
* VK_EXT_descriptor_indexing (v0.0.2)
* VK_EXT_extended_dynamic_state (v0.0.1)
* VK_EXT_extended_dynamic_state2 (v0.0.1)
* VK_EXT_external_memory_dma_buf (v0.0.1)
* VK_EXT_global_priority (v0.0.2)
* VK_EXT_global_priority_query (v0.0.1)
* VK_EXT_graphics_pipeline_library (v0.0.1)
* VK_EXT_host_query_reset (v0.0.1)
* VK_EXT_image_2d_view_of_3d (v0.0.1)
* VK_EXT_image_drm_format_modifier (v0.0.2)
* VK_EXT_image_robustness (v0.0.1)
* VK_EXT_image_view_min_lod (v0.0.1)
* VK_EXT_index_type_uint8 (v0.0.1)
* VK_EXT_inline_uniform_block (v0.0.1)
* VK_EXT_line_rasterization (v0.0.1)
* VK_EXT_load_store_op_none (v0.0.1)
* VK_EXT_memory_budget (v0.0.1)
* VK_EXT_multi_draw (v0.0.1)
* VK_EXT_mutable_descriptor_type (v0.0.1)
* VK_EXT_non_seamless_cube_map (v0.0.1)
* VK_EXT_pipeline_creation_cache_control (v0.0.3)
* VK_EXT_pipeline_creation_feedback (v0.0.1)
* VK_EXT_primitive_topology_list_restart (v0.0.1)
* VK_EXT_primitives_generated_query (v0.0.1)
* VK_EXT_private_data (v0.0.1)
* VK_EXT_provoking_vertex (v0.0.1)
* VK_EXT_queue_family_foreign (v0.0.1)
* VK_EXT_rasterization_order_attachment_access (v0.0.1)
* VK_EXT_robustness2 (v0.0.1)
* VK_EXT_sampler_filter_minmax (v0.0.2)
* VK_EXT_scalar_block_layout (v0.0.1)
* VK_EXT_separate_stencil_usage (v0.0.1)
* VK_EXT_shader_demote_to_helper_invocation (v0.0.1)
* VK_EXT_shader_module_identifier (v0.0.1)
* VK_EXT_shader_stencil_export (v0.0.1)
* VK_EXT_shader_viewport_index_layer (v0.0.1)
* VK_EXT_subgroup_size_control (v0.0.2)
* VK_EXT_texel_buffer_alignment (v0.0.1)
* VK_EXT_tooling_info (v0.0.1)
* VK_EXT_transform_feedback (v0.0.1)
* VK_EXT_vertex_attribute_divisor (v0.0.3)
* VK_EXT_vertex_input_dynamic_state (v0.0.2)
* VK_AMD_buffer_marker (v0.0.1)
* VK_KHR_swapchain (v0.0.70)
* VK_ARM_rasterization_order_attachment_access (v0.0.1)
* VK_VALVE_mutable_descriptor_type (v0.0.1)
Traits:
* Supports U8 Indices: true
* Supports Sampler Mirror Clamp To Edge: false
* Supports Sampler Reduction Mode: true
* Supports Custom Border Color (Without Format): true
* Supports Anisotropic Filtering: true
* Supports Last Provoking Vertex: true
* Supports Logical Operations: true
* Supports Vertex Attribute Divisor: true
* Supports Vertex Attribute Zero Divisor: true
* Supports Push Descriptors: true
* Supports Imageless Framebuffers: true
* Supports Global Priority: true
* Supports Multiple Viewports: true
* Supports Shader Viewport Index: true
* Supports SPIR-V 1.4: true
* Supports Shader Invocation Demotion: true
* Supports 16-bit FP: true
* Supports 8-bit Integers: false
* Supports 16-bit Integers: true
* Supports 64-bit Integers: false
* Supports Atomic 64-bit Integers: false
* Supports Floating Point Behavior Control: true
* Supports Image Read Without Format: true
* Supports List Primitive Topology Restart: true
* Supports Patch List Primitive Topology Restart: false
* Supports Transform Feedback: true
* Supports Geometry Shaders: true
*  Supports Vertex Pipeline Stores and Atomics: true
* Supports Fragment Stores and Atomics: true
* Supports Shader Storage Image Write Without Format: true
*Supports Subgroup Vote: true
* Subgroup Size: 128
* BCn Support: 1111111
Quirks:
* Needs Individual Texture Binding Writes: false
* VkImage Mutable Format is costly: true
* Adreno Relaxed Format Aliasing: true
* Adreno Broken Format Reporting: false
* Broken Descriptor Aliasing: false
* Relaxed Render Pass Compatibility: false
* Max Subpass Count: 4294967295
* Max Global Queue Priority: Medium
I92EmuMainLaunching ROM content://com.android.externalstorage.documents/tree/primary%3ASwitch%20rom/document/primary%3ASwitch%20rom%2FPokemon_Lets_Go_Pikachu_v1.0.2_EUR_%5Brpgarchive.net%5D.xci
I111EmuMainLoadExeFs: Loaded 'rtld.nso' at 0x800000000 (.text @ 0x800001000)
I362EmuMainLoadExeFs: Loaded 'main.nso' at 0x800005000 (.text @ 0x800006000)
I465EmuMainLoadExeFs: Loaded 'subsdk0.nso' at 0x801EE7000 (.text @ 0x801EE8000)
I510EmuMainLoadExeFs: Loaded 'subsdk1.nso' at 0x802D12000 (.text @ 0x802D13000)
I584EmuMainLoadExeFs: Loaded 'sdk.nso' at 0x80340B000 (.text @ 0x80340C000)
I636HOS-0ICommonStateGetter: Switch to mode: Handheld
W643HOS-0HandleRequest: Cannot find HIPC function in service 'am::IApplicationFunctions': 0x16 (22)
E644HOS-0Break: Exit Stack Trace (0)
* 0x714EAC0D14 (skyline::kernel::svc::Break(skyline::DeviceState const&) from libskyline.so)
* 0x714EAA3380 (skyline::nce::NCE::SvcHandler(unsigned short, skyline::nce::ThreadContext*) from libskyline.so)
* 0x80340B0B8 (from sdk.nso.patch)
* 0x803458780 (nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...) from sdk.nso)
* 0x803458844 (from sdk.nso)
* 0x803483BD4 (nn::fs::MountRom(char const*, void*, unsigned long) from sdk.nso)
* 0x80002A6E8 (from main.nso)
* 0x80002A620 (from main.nso)
* 0x80000D8A0 (from main.nso)
* 0x80003F00C (from main.nso)
* 0x80000BC3C (from main.nso)
* 0x80003F31C (from main.nso)
* 0x80000A900 (nnMain from main.nso)
* 0x8034909BC (nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)()) from sdk.nso)
* 0x8000010AC (from rtld.nso)

**Comment by NihalPadwal** [comment] 2022-09-25 17:23
![Uploading Screenshot_2022-09-25-22-45-55-63_fcf072b9e4efc4ce5ca3e36691a7c3c6.jpg…]()

**Comment by MuhSlam** [comment] 2022-09-25 18:24
There is already issue of this game on the list #336 ... You can comment your results there , not to duplicate it

**Comment by Crytonics** [comment] 2022-09-25 18:36
Duplicate of #336

**Closed by Crytonics** 2022-09-25 18:36 UTC

**Comment by Crytonics** [comment] 2022-09-25 18:40
@NihalPadwal You are banned from the repository because your log contains a name of a piracy website.

**Comment by Priyanshtyu** [comment] 2022-10-23 02:27
Gyhi
