### ISSUE TITLE
Pacman championship 2, very low fps in menus and audio missing

### ISSUE THREAD

**Issue by washingleavesandthensome23-434** [skyline-emu/skyline-games-list#1366] opened 2023-01-16 09:29 UTC
Is there an existing issue for this?
 I have searched the existing issues, nothing found

Tested Build
Edge 24

Android Version
13

SoC type
Snapdragon

Device GSMArena link
https://m.gsmarena.com/samsung_galaxy_z_flip4-11538.php

Game Behaviour
As described , am getting very low fps and no audio in-game in pacman championship 2 

Docked or Undocked, no difference noticed.
Max Executor slots
Max Flush. 
Enabled max GPU clocks.

Is Log Level is set to 'Info'?
 Yes
Log file
[emulation.txt](https://github.com/skyline-emu/skyline-games-list/files/10424383/emulation.txt)
![Screenshot_20230116_103229](https://user-images.githubusercontent.com/60486562/212645406-bd69be3c-c76f-45b9-a72e-d22dff20ef7d.jpg)
![Screenshot_20230116_103211](https://user-images.githubusercontent.com/60486562/212645410-9a47c23d-65a3-4c4e-ba42-1b427d0a634c.jpg)

**Comment by Crytonics** [comment] 2023-01-16 14:47
Duplicate of #682

**Closed by Crytonics** 2023-01-16 14:47 UTC
