### ISSUE TITLE
Cuphead

### ISSUE THREAD

**Issue by Sirox228** [skyline-emu/skyline-games-list#895] opened 2022-08-05 21:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1269

### Android Version

11

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_f2_pro-10220.php

### Game Behaviour

I searched for an issue about this game and there's one of it, but i need to report an issue.
• was working in old versions of skyline
• not working in current version (check tested build) in both handheld and docked modes, also i used default driver

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/9271638/emulation.zip)

**Comment by Silverdragon122** [comment] 2022-08-05 21:07
Please dont make duplicates

**Comment by Crytonics** [comment] 2022-08-05 21:14
Duplicate of #23

**Comment by Crytonics** [comment] 2022-08-05 21:14
You can post comment there

**Closed by Crytonics** 2022-08-05 21:14 UTC

**Comment by maiodin** [comment] 2022-10-20 09:54
The game doesnt auto save.
Other than that runs perfect with minor freezes.
Using samsung fold 2

**Comment by Isaac7800** [comment] 2023-02-24 17:47
Hol

**Comment by Isaac7800** [comment] 2023-02-24 17:47
Holl

**Comment by Isaac7800** [comment] 2023-02-24 17:47
Holl

**Comment by Simplementemanuel** [comment] 2023-03-17 20:47
Si tienes un SD680 no te recomiendo jugarlo ya que el teléfono puede crashearse

**Comment by Angelreyes182** [comment] 2023-09-15 16:35
Como descargar
