### ISSUE TITLE
Undertale Glitches 

### ISSUE THREAD

**Issue by EliasGerliz** [skyline-emu/skyline-games-list#1219] opened 2022-11-28 18:23 UTC
Hey there!
I have some Glitches at Undertale (My device is Redmi Note 10 Pro - Snapdragon 732G - 8 GB RAM
![Screenshot_2022-11-28-15-06-31-550_skyline emu](https://user-images.githubusercontent.com/114945583/204352110-7d1390f5-eaa6-4df0-aada-ef73ec420f66.jpg)
How to fix it?

**Comment by EZonTheEyes** [comment] 2022-11-30 08:02
Duplicate of #427 and incorrect formatting. To ask for support in games we reccomend using the skyline discord for questions. 
Also these are known glitches with no current fix.

**Closed by EZonTheEyes** 2022-11-30 08:02 UTC
