### ISSUE TITLE
[Support and Bug fixes Request] My Little Pony: A Maretime Bay Adventure Latest version of the game

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [skyline-emu/skyline-games-list#1105] opened 2022-09-28 15:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

skyline-1353-debug

### Android Version

12

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/xiaomi_11_lite_5g_ne-11101.php

### Game Behaviour

"-Game is not bootable, FPS and GPU are not active during boot"

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

Here is the complete log info (This issue is created some time ago by someone else but with incomplete logs - this logs will show everything from starting the app to the unbootable game problem)

[emulation.sklog](https://github.com/skyline-emu/skyline-games-list/files/9666477/emulation.sklog.zip)

**Comment by admin-elvistrujanovic** [comment] 2022-09-28 15:20
This is edited issue with some more log informations and added one more device to be supported for this game - first created issue is from #1058

**Comment by Crytonics** [comment] 2022-09-28 18:34
Duplicate of #1058

**Comment by Crytonics** [comment] 2022-09-28 18:35
You can comment there and add more info about game.

**Closed by Crytonics** 2022-09-28 18:34 UTC

**Comment by admin-elvistrujanovic** [comment] 2022-09-28 19:18
> You can comment there and add more info about game.

Ok, I did that via screenshots and those links (ported from this issue to the original one) so is this ok now?
