### ISSUE TITLE
Kirby star allies

### ISSUE THREAD

**Issue by Radnu008** [skyline-emu/skyline-games-list#1549] opened 2023-04-18 15:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Edge 65

### Android Version

13

### SoC type

Other

### Device GSMArena link

Redmi note 9 pro

### Game Behaviour

When I get in the level, Kirby just guards himself the whole time and I'm not controlling it and the screen is glitchy so i would like you to fix the behaviours.

Thank you
![Screenshot_2023-04-18-16-51-13-092_skyline emu](https://user-images.githubusercontent.com/131180606/232819145-d0835be1-e236-402b-a361-161f82539d7b.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

https://github.com/skyline-emu/skyline-games-list/files/9380917/Kirby.Star.Allies.zip

**Comment by RPYgamers** [comment] 2023-04-18 15:11
Duplicate of #972
Use search next time

**Closed** 2023-04-18 20:09 UTC
