### ISSUE TITLE
Maneater                                                                               

### ISSUE THREAD

**Issue by Mim2414** [skyline-emu/skyline-games-list#1030] opened 2022-08-28 19:46 UTC
Is there an existing issue for this ?                                                                                               - [ ] I have searched the existing issues                                                                                                                       Tested Build                                                                              CI #1332                                                                                          Android Version                                                                                                    12                                                                                                                           SoC type                                                                                               Snapdragon                                                                                                                                     Device GSMArena link                                                                       https://m.gsmarena.com/xiaomi_poco_x3_pro-10802.php                                                                                                                                                     Game Behaviour                                                               now loading screen then freeze                                                                        ![Screenshot_2022-08-28-20-24-43-541_skyline.emu.jpg](https://user-images.githubusercontent.com/103127257/187091623-2d0bed47-9a4f-48a9-a6d9-37afce136cd4.jpg)                                                                   Is Log Level is set to ' Info ' ?                                       - [ ] YES                                                                               Log file                                                                                  I90EmuMainCreateDevice: Vulkan Device:
Name: Turnip Adreno (TM) 640
Type: IntegratedGpu
Driver ID: MesaTurnip
Vulkan Version: 1.2.224
Driver Version: 22.2.99
Queues:
* 1xGCT--: TSB48 MIG(1x1x1) <--
Extensions:
* VK_KHR_incremental_present (v0.0.1)
* VK_EXT_hdr_metadata (v0.0.2)
* VK_GOOGLE_display_timing (v0.0.1)
* VK_KHR_bind_memory2 (v0.0.1)
* VK_KHR_buffer_device_address (v0.0.1)
* VK_KHR_copy_commands2 (v0.0.1)
* VK_KHR_create_renderpass2 (v0.0.1)
* VK_KHR_dedicated_allocation (v0.0.3)
* VK_KHR_depth_stencil_resolve (v0.0.1)
* VK_KHR_descriptor_update_template (v0.0.1)
* VK_KHR_device_group (v0.0.4)
* VK_KHR_draw_indirect_count (v0.0.1)
* VK_KHR_driver_properties (v0.0.1)
* VK_KHR_external_fence (v0.0.1)
* VK_KHR_external_fence_fd (v0.0.1)
* VK_KHR_external_memory (v0.0.1)
* VK_KHR_external_memory_fd (v0.0.1)
* VK_KHR_external_semaphore (v0.0.1)
* VK_KHR_external_semaphore_fd (v0.0.1)
* VK_KHR_get_memory_requirements2 (v0.0.1)
* VK_KHR_image_format_list (v0.0.1)
* VK_KHR_imageless_framebuffer (v0.0.1)
* VK_KHR_maintenance1 (v0.0.2)
* VK_KHR_maintenance2 (v0.0.1)
* VK_KHR_maintenance3 (v0.0.1)
* VK_KHR_multiview (v0.0.1)
* VK_KHR_pipeline_executable_properties (v0.0.1)
* VK_KHR_push_descriptor (v0.0.2)
* VK_KHR_relaxed_block_layout (v0.0.1)
* VK_KHR_sampler_mirror_clamp_to_edge (v0.0.3)
* VK_KHR_sampler_ycbcr_conversion (v0.0.14)
* VK_KHR_separate_depth_stencil_layouts (v0.0.1)
* VK_KHR_shader_draw_parameters (v0.0.1)
* VK_KHR_shader_float16_int8 (v0.0.1)
* VK_KHR_shader_float_controls (v0.0.4)
* VK_KHR_shader_integer_dot_product (v0.0.1)
* VK_KHR_shader_non_semantic_info (v0.0.1)
* VK_KHR_shader_subgroup_extended_types (v0.0.1)
* VK_KHR_shader_terminate_invocation (v0.0.1)
* VK_KHR_spirv_1_4 (v0.0.1)
* VK_KHR_storage_buffer_storage_class (v0.0.1)
* VK_KHR_synchronization2 (v0.0.1)
* VK_KHR_uniform_buffer_standard_layout (v0.0.1)
* VK_KHR_variable_pointers (v0.0.1)
* VK_KHR_vulkan_memory_model (v0.0.3)
* VK_KHR_zero_initialize_workgroup_memory (v0.0.1)
* VK_EXT_4444_formats (v0.0.1)
* VK_EXT_border_color_swizzle (v0.0.1)
* VK_EXT_color_write_enable (v0.0.1)
* VK_EXT_conditional_rendering (v0.0.2)
* VK_EXT_custom_border_color (v0.0.12)
* VK_EXT_depth_clip_control (v0.0.1)
* VK_EXT_depth_clip_enable (v0.0.1)
* VK_EXT_descriptor_indexing (v0.0.2)
* VK_EXT_extended_dynamic_state (v0.0.1)
* VK_EXT_extended_dynamic_state2 (v0.0.1)
* VK_EXT_external_memory_dma_buf (v0.0.1)
* VK_EXT_host_query_reset (v0.0.1)
* VK_EXT_image_2d_view_of_3d (v0.0.1)
* VK_EXT_image_drm_format_modifier (v0.0.2)
* VK_EXT_image_robustness (v0.0.1)
* VK_EXT_image_view_min_lod (v0.0.1)
* VK_EXT_index_type_uint8 (v0.0.1)
* VK_EXT_line_rasterization (v0.0.1)
* VK_EXT_load_store_op_none (v0.0.1)
* VK_EXT_memory_budget (v0.0.1)
* VK_EXT_pipeline_creation_cache_control (v0.0.3)
* VK_EXT_pipeline_creation_feedback (v0.0.1)
* VK_EXT_primitive_topology_list_restart (v0.0.1)
* VK_EXT_primitives_generated_query (v0.0.1)
* VK_EXT_private_data (v0.0.1)
* VK_EXT_provoking_vertex (v0.0.1)
* VK_EXT_queue_family_foreign (v0.0.1)
* VK_EXT_robustness2 (v0.0.1)
* VK_EXT_sampler_filter_minmax (v0.0.2)
* VK_EXT_scalar_block_layout (v0.0.1)
* VK_EXT_separate_stencil_usage (v0.0.1)
* VK_EXT_shader_demote_to_helper_invocation (v0.0.1)
* VK_EXT_shader_module_identifier (v0.0.1)
* VK_EXT_shader_stencil_export (v0.0.1)
* VK_EXT_shader_viewport_index_layer (v0.0.1)
* VK_EXT_subgroup_size_control (v0.0.2)
* VK_EXT_texel_buffer_alignment (v0.0.1)
* VK_EXT_transform_feedback (v0.0.1)
* VK_EXT_vertex_attribute_divisor (v0.0.3)
* VK_EXT_vertex_input_dynamic_state (v0.0.2)
* VK_AMD_buffer_marker (v0.0.1)
* VK_KHR_swapchain (v0.0.70)
* VK_ARM_rasterization_order_attachment_access (v0.0.1)
* VK_VALVE_mutable_descriptor_type (v0.0.1)
Traits:
* Supports U8 Indices: true
* Supports Sampler Mirror Clamp To Edge: false
* Supports Sampler Reduction Mode: true
* Supports Custom Border Color (Without Format): true
* Supports Anisotropic Filtering: true
* Supports Last Provoking Vertex: true
* Supports Logical Operations: true
* Supports Vertex Attribute Divisor: true
* Supports Vertex Attribute Zero Divisor: true
* Supports Push Descriptors: true
* Supports Imageless Framebuffers: true
* Supports Global Priority: false
* Supports Multiple Viewports: true
* Supports Shader Viewport Index: true
* Supports SPIR-V 1.4: true
* Supports Shader Invocation Demotion: true
* Supports 16-bit FP: true
* Supports 8-bit Integers: false
* Supports 16-bit Integers: true
* Supports 64-bit Integers: false
* Supports Atomic 64-bit Integers: false
* Supports Floating Point Behavior Control: true
* Supports Image Read Without Format: true
* Supports List Primitive Topology Restart: true
* Supports Patch List Primitive Topology Restart: false
* Supports Transform Feedback: true
* Supports Geometry Shaders: true
*  Supports Vertex Pipeline Stores and Atomics: true
* Supports Fragment Stores and Atomics: true
* Supports Shader Storage Image Write Without Format: true
*Supports Subgroup Vote: true
* Subgroup Size: 128
* BCn Support: 1111111
Quirks:
* Needs Individual Texture Binding Writes: false
* VkImage Mutable Format is costly: true
* Adreno Relaxed Format Aliasing: true
* Adreno Broken Format Reporting: false
* Broken Descriptor Aliasing: false
* Relaxed Render Pass Compatibility: false
* Max Subpass Count: 4294967295
* Max Global Queue Priority: Medium
I196EmuMainLaunching ROM content://com.android.externalstorage.documents/tree/0123-4567%3ANINTENDO%20SWITCH%20GAMES%202022/document/0123-4567%3ANINTENDO%20SWITCH%20GAMES%202022%2FManeater%20%5B010093D00CB22000%5D%5Bv0%5DROMSLAB.nsp
I360EmuMainLoadExeFs: Loaded 'rtld.nso' at 0x800000000 (.text @ 0x800001000)
I1644EmuMainLoadExeFs: Loaded 'main.nso' at 0x800005000 (.text @ 0x800006000)
I1738EmuMainLoadExeFs: Loaded 'subsdk0.nso' at 0x807944000 (.text @ 0x807945000)
I1892EmuMainLoadExeFs: Loaded 'sdk.nso' at 0x807FF6000 (.text @ 0x807FF7000)
I1946HOS-0ICommonStateGetter: Switch to mode: Docked
I1947HOS-0SwitchPlatformMemory.cpp:L199:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: MemInfo.totalAvailableMemorySize = 4143972352 [3952 MB]
I1947HOS-0SwitchPlatformMemory.cpp:L200:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: MemInfo.totalUsedMemorySize = 151064576 [144 MB]
I1947HOS-0SwitchPlatformMemory.cpp:L201:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: MemInfo.totalMemoryHeapSize = 0 [0 MB]
I1947HOS-0SwitchPlatformMemory.cpp:L202:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: MemInfo.allocatedMemoryHeapSize = 0 [0 MB]
I1947HOS-0SwitchPlatformMemory.cpp:L203:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: MemInfo.programSize = 150994944 [144 MB]
I1947HOS-0SwitchPlatformMemory.cpp:L204:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: MemInfo.totalThreadStackSize = 69632 [0 MB]
I1947HOS-0SwitchPlatformMemory.cpp:L205:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: MemInfo.threadCount = 2
I1947HOS-0SwitchPlatformMemory.cpp:L206:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: 
I1947HOS-0SwitchPlatformMemory.cpp:L223:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: Using MallocBinned3.
I1947HOS-0SwitchPlatformMemory.cpp:L274:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: OS (malloc) Heap = 4194304 [4 MB]
I1947HOS-0SwitchPlatformMemory.cpp:L295:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: Available Physical Memory = 3986685952 [3802 MB]
I1947HOS-0SwitchPlatformMemory.cpp:L296:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: Available Virtual Address Space = 66571993088 [63488 MB]
I1947HOS-0SwitchPlatformMemory.cpp:L367:Maneater-Switch-Shipping:StaticInit():MainThread:1124403s: 
I1950HOS-0SwitchPlatformMemory.cpp:L730:Maneater-Switch-Shipping:FPageCaches():MainThread:1124403s: Total 3984519168 bytes available for the page cache.
I1950HOS-0SwitchPlatformMemory.cpp:L688:Maneater-Switch-Shipping:Close():MainThread:1124403s: FBootAllocator used 4129824 out of 4326432 bytes of memory, wasting 196608 bytes.
I1954HOS-0SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():MainThread:1124403s: Used memory before allocating anything was 152.07MB
I1987HOS-2SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():GameThread:1124403s: 
-----FILE SYSTEM STARTUP-----
I1998HOS-2SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():GameThread:1124403s: Shipping build disallows Host and SD functions (can't be used in a submittable build)...
I1998HOS-2SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():GameThread:1124403s: Loading command line rom:/UE4CommandLine.txt. Success? 1
I1999HOS-2SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():GameThread:1124403s: Checking for AddOnContent...
I1999HOS-2SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():GameThread:1124403s: CountAddOnCountent -> 0
I1999HOS-2SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():GameThread:1124403s: ListAddOnCountent -> 0
I1999HOS-2SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():GameThread:1124403s: Read mount point: 'rom:'
I1999HOS-2SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():GameThread:1124403s: Write mount point: 'rom:'
I1999HOS-2SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():GameThread:1124403s: -----FILE SYSTEM STARTUP-----

I1999HOS-2SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():GameThread:1124403s: Switch CommandLine :  ../../../Maneater/Maneater.uproject 
I2013HOS-2SwitchSocketSubsystem.cpp:L28:Maneater-Switch-Shipping:FSwitchSocketSubsystem_StaticInit():GameThread:1124403s: Is Network already availble? 0
I2013HOS-2SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():GameThread:1124403s: Project file not found: ../../../Maneater/Maneater.uproject
I2017HOS-3SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():Switch AddOnContent Thread:1124403s: Checking for AddOnContent...
I2017HOS-3SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():Switch AddOnContent Thread:1124403s: CountAddOnCountent -> 0
I2017HOS-3SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():Switch AddOnContent Thread:1124403s: ListAddOnCountent -> 0
I2679HOS-2SwitchPlatformMisc.cpp:L177:Maneater-Switch-Shipping:LocalPrint():GameThread:1124403s: FOnlineSubsystemSwitch::Init
I2708HOS-2SetCpuBoostMode: Set CPU boost mode to Fast Load
W2736HOS-2HandleRequest: Cannot find function in service 'hid::IHidServer': 0x1F (31)
W2736HOS-2HandleRequest: Cannot find function in service 'hid::IHidServer': 0x15 (21)
I2736HOS-2SetPerformanceConfiguration: Performance configuration set to 0x20004 (Handheld)
I2736HOS-2SetPerformanceConfiguration: Performance configuration set to 0x10001 (Docked)
W3193GPFIFOCopyPitchToBlockLinear: DMA copy width mismatch: src: 4 dst: 64
W3193GPFIFOCopyPitchToBlockLinear: DMA copy width mismatch: src: 4 dst: 64
W3193GPFIFOCopyPitchToBlockLinear: DMA copy width mismatch: src: 4 dst: 64
W3193GPFIFOCopyPitchToBlockLinear: DMA copy width mismatch: src: 4 dst: 64
W3193GPFIFOCopyPitchToBlockLinear: DMA copy width mismatch: src: 4 dst: 64
W3193GPFIFOCopyPitchToBlockLinear: DMA copy width mismatch: src: 4 dst: 64
W3193GPFIFOCopyPitchToBlockLinear: DMA copy width mismatch: src: 4 dst: 64
W3193GPFIFOCopyPitchToBlockLinear: DMA copy width mismatch: src: 4 dst: 64
W3193GPFIFOCopyPitchToBlockLinear: DMA copy width mismatch: src: 4 dst: 64
W3193GPFIFOCopyPitchToBlockLinear:

**Comment by Crytonics** [comment] 2022-08-28 21:46
Duplicate of #705

**Comment by Crytonics** [comment] 2022-08-28 21:46
@Mim2414 you are banned from the repository because your log contains a name of a piracy website.

**Closed by Crytonics** 2022-08-28 21:46 UTC
