### ISSUE TITLE
Littlewood

### ISSUE THREAD

**Issue by GhostLm** [skyline-emu/skyline-games-list#872] opened 2022-07-24 19:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1254

### Android Version

10

### SoC type

Snapdragon

### Device GSMArena link

https://www.gsmarena.com/tcl_10_5g_uw-10559.php

### Game Behaviour

Mountains are invisible, indoors 60 FPS outdoors 30 FPS 
![image](https://user-images.githubusercontent.com/103976700/180663483-6fbfbe87-cdd2-4895-b2cb-5040f5b838b1.png)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.zip](https://github.com/skyline-emu/skyline-games-list/files/9176567/emulation.zip)

**Comment by MuhSlam** [comment] 2022-07-24 20:00
This game already exist on list 
You etter closed it 
Use search tool next time

**Comment by GhostLm** [comment] 2022-07-24 20:04
> This game already exist on list You etter closed it Use search tool next time

if it exists but it is outdated, the game is already working although with graphic errors

**Comment by MuhSlam** [comment] 2022-07-24 20:09
You better comment on there .. 
With new screenshot and gameplay video 
not make same list again

**Comment by MuhSlam** [comment] 2022-07-24 20:12
@Crytonics 
Handle this guy
He insisted not to close this issue
It's double

**Comment by Crytonics** [comment] 2022-07-24 21:38
Duplicate of #569

**Comment by Crytonics** [comment] 2022-07-24 21:38
You can comment there for updates.

**Closed by Crytonics** 2022-07-24 21:38 UTC
