### ISSUE TITLE
Crash ™ Team Racing Nitro-Fueled

### ISSUE THREAD

**Issue by Yusefsar** [skyline-emu/skyline-games-list#1482] opened 2023-03-12 12:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

Skyline  v2089

### Android Version

13

### SoC type

Mediatek

### Device GSMArena link

https://m.gsmarena.com/xiaomi_poco_x4_gt-ampp-11626.php

### Game Behaviour

Game crashes in loading screen after entering game

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

I11EmuMainCreateDevice: Vulkan Device:
Name: Mali-G610 MC6
Type: IntegratedGpu
Driver ID: ArmProprietary
Vulkan Version: 1.1.177
Driver Version: 32.1.0
Queues:
* 2xGCT--: TSB64 MIG(1x1x1) <--
Extensions:
* VK_KHR_incremental_present (v0.0.2)
* VK_KHR_shared_presentable_image (v0.0.1)
* VK_GOOGLE_display_timing (v0.0.1)
* VK_KHR_16bit_storage (v0.0.1)
* VK_KHR_8bit_storage (v0.0.1)
* VK_KHR_bind_memory2 (v0.0.1)
* VK_KHR_buffer_device_address (v0.0.1)
* VK_KHR_create_renderpass2 (v0.0.1)
* VK_KHR_dedicated_allocation (v0.0.3)
* VK_KHR_depth_stencil_resolve (v0.0.1)
* VK_KHR_descriptor_update_template (v0.0.1)
* VK_KHR_device_group (v0.0.4)
* VK_KHR_draw_indirect_count (v0.0.1)
* VK_KHR_driver_properties (v0.0.1)
* VK_KHR_external_fence (v0.0.1)
* VK_KHR_external_fence_fd (v0.0.1)
* VK_KHR_external_memory (v0.0.1)
* VK_KHR_external_memory_fd (v0.0.1)
* VK_KHR_external_semaphore (v0.0.1)
* VK_KHR_external_semaphore_fd (v0.0.1)
* VK_KHR_get_memory_requirements2 (v0.0.1)
* VK_KHR_image_format_list (v0.0.1)
* VK_KHR_imageless_framebuffer (v0.0.1)
* VK_KHR_maintenance1 (v0.0.2)
* VK_KHR_maintenance2 (v0.0.1)
* VK_KHR_maintenance3 (v0.0.1)
* VK_KHR_multiview (v0.0.1)
* VK_KHR_relaxed_block_layout (v0.0.1)
* VK_KHR_sampler_mirror_clamp_to_edge (v0.0.3)
* VK_KHR_sampler_ycbcr_conversion (v0.0.14)
* VK_KHR_separate_depth_stencil_layouts (v0.0.1)
* VK_KHR_shader_draw_parameters (v0.0.1)
* VK_KHR_shader_float16_int8 (v0.0.1)
* VK_KHR_shader_float_controls (v0.0.4)
* VK_KHR_shader_non_semantic_info (v0.0.1)
* VK_KHR_shader_subgroup_extended_types (v0.0.1)
* VK_KHR_spirv_1_4 (v0.0.1)
* VK_KHR_storage_buffer_storage_class (v0.0.1)
* VK_KHR_timeline_semaphore (v0.0.2)
* VK_KHR_uniform_buffer_standard_layout (v0.0.1)
* VK_KHR_variable_pointers (v0.0.1)
* VK_KHR_vulkan_memory_model (v0.0.3)
* VK_EXT_astc_decode_mode (v0.0.1)
* VK_EXT_calibrated_timestamps (v0.0.2)
* VK_EXT_descriptor_indexing (v0.0.2)
* VK_EXT_fragment_density_map (v0.0.1)
* VK_EXT_fragment_density_map2 (v0.0.1)
* VK_EXT_global_priority (v0.0.2)
* VK_EXT_host_query_reset (v0.0.1)
* VK_EXT_image_robustness (v0.0.1)
* VK_EXT_index_type_uint8 (v0.0.1)
* VK_EXT_inline_uniform_block (v0.0.1)
* VK_EXT_line_rasterization (v0.0.1)
* VK_EXT_provoking_vertex (v0.0.1)
* VK_EXT_queue_family_foreign (v0.0.1)
* VK_EXT_device_memory_report (v0.0.2)
* VK_EXT_sampler_filter_minmax (v0.0.2)
* VK_EXT_scalar_block_layout (v0.0.1)
* VK_EXT_separate_stencil_usage (v0.0.1)
* VK_EXT_subgroup_size_control (v0.0.2)
* VK_EXT_texture_compression_astc_hdr (v0.0.1)
* VK_EXT_shader_subgroup_ballot (v0.0.1)
* VK_EXT_shader_subgroup_vote (v0.0.1)
* VK_EXT_transform_feedback (v0.0.1)
* VK_EXT_external_memory_dma_buf (v0.0.1)
* VK_EXT_image_drm_format_modifier (v0.0.1)
* VK_EXT_custom_border_color (v0.0.12)
* VK_ANDROID_external_memory_android_hardware_buffer (v0.0.3)
* VK_KHR_swapchain (v0.0.70)
* VK_EXT_4444_formats (v0.0.1)
Traits:
* Supports U8 Indices: true
* Supports Sampler Mirror Clamp To Edge: false
* Supports Sampler Reduction Mode: true
* Supports Custom Border Color (Without Format): true
* Supports Anisotropic Filtering: true
* Supports Last Provoking Vertex: true
* Supports Logical Operations: false
* Supports Vertex Attribute Divisor: false
* Supports Vertex Attribute Zero Divisor: false
* Supports Push Descriptors: false
* Supports Imageless Framebuffers: true
* Supports Global Priority: true
* Supports Multiple Viewports: false
* Supports Shader Viewport Index: false
* Supports SPIR-V 1.4: true
* Supports Shader Invocation Demotion: false
* Supports 16-bit FP: true
* Supports 8-bit Integers: true
* Supports 16-bit Integers: true
* Supports 64-bit Integers: false
* Supports Atomic 64-bit Integers: false
* Supports Floating Point Behavior Control: true
* Supports Image Read Without Format: true
* Supports List Primitive Topology Restart: false
* Supports Patch List Primitive Topology Restart: false
* Supports Transform Feedback: false
* Supports Geometry Shaders: true
*  Supports Vertex Pipeline Stores and Atomics: false
* Supports Fragment Stores and Atomics: true
* Supports Shader Storage Image Write Without Format: true
*Supports Subgroup Vote: true
* Subgroup Size: 16
* BCn Support: 0000000
Quirks:
* Needs Individual Texture Binding Writes: false
* VkImage Mutable Format is costly: true
* Adreno Relaxed Format Aliasing: false
* Adreno Broken Format Reporting: false
* Broken Descriptor Aliasing: false
* Relaxed Render Pass Compatibility: false
* Max Subpass Count: 4294967295
* Max Global Queue Priority: High
I538EmuMainPipelineManager: Loaded 795 graphics pipelines in 376ms
I538EmuMainNPDM Metadata:
Title: ID: 100F9F00C696000, Version: 0
Main Thread: Priority: 44, Stack Size: 0x100000
Scheduler: Ideal Core: 0, Core Mask: 0111, Priority: 28 - 59
Kernel Version: v9.1
I540EmuMainSerialisePipelineCache: Wrote Vulkan pipeline cache to /storage/emulated/0/Android/data/skyline.emu/files/vk_graphics_pipeline_cache/0100F9F00C696000/B5130000000067A80010000892FD853D0ADE495985DBDAD39586D9E9 (size: 0x2AC06 bytes)
I542EmuMainLoadExeFs: Loaded 'rtld.nso' at 0x800000000 (.text @ 0x800001000)
I888EmuMainLoadExeFs: Loaded 'main.nso' at 0x800005000 (.text @ 0x800007000)
I928EmuMainLoadExeFs: Loaded 'subsdk0.nso' at 0x8051F7000 (.text @ 0x8051F8000)
I984EmuMainLoadExeFs: Loaded 'sdk.nso' at 0x805A67000 (.text @ 0x805A69000)
I984EmuMainStarting "Crash鈩� Team Racing Nitro-Fueled" (0100F9F00C696000) v1.0.0 by "Activision Publishing, Inc."
I984EmuMainExecute: Starting main HOS thread
I1017HOS-1ICommonStateGetter: Switch to mode: Docked
I1023HOS-1code\engine\shared\core\common\report\igReportHandler.cpp:L147:game-nx-fin:igReportPrint():MainThread:427780s: Total System Heap Available to Program:  3860 MB
I1023HOS-1code\engine\shared\core\common\report\igReportHandler.cpp:L147:game-nx-fin:igReportPrint():MainThread:427780s:      Total Size of Program code & data:   106 MB
I1023HOS-1code\engine\shared\core\common\report\igReportHandler.cpp:L147:game-nx-fin:igReportPrint():MainThread:427780s: Allocated 2843 MB from OS
I1041HOS-1code\engine\shared\core\common\report\igReportHandler.cpp:L147:game-nx-fin:igReportPrint():MainThread:427780s: Allocating 690 mb as VRAM A.
I1041HOS-1code\engine\shared\core\common\report\igReportHandler.cpp:L147:game-nx-fin:igReportPrint():MainThread:427780s: Allocating 145 mb as VRAM B.
W1061HOS-1HandleRequest: Cannot find HIPC function in service 'nifm::IRequest': 0x3 (3)
I1140HOS-1code\engine\shared\core\common\report\igReportHandler.cpp:L147:game-nx-fin:igReportPrint():MainThread:427780s: app:/archives/update.pak not found.
I1282HOS-1code\engine\shared\core\common\report\igReportHandler.cpp:L147:game-nx-fin:igReportPrint():MainThread:427781s: Display Resolution: 1280x720
I1283HOS-1code\engine\shared\core\common\report\igReportHandler.cpp:L147:game-nx-fin:igReportPrint():MainThread:427781s: Initialized NVN SDK 53.310.
I2083HOS-1SetPerformanceConfiguration: Performance configuration set to 0x10001 (Docked)
I2083HOS-1SetPerformanceConfiguration: Performance configuration set to 0x20004 (Handheld)
I4494HOS-1code\engine\shared\core\common\report\igReportHandler.cpp:L147:game-nx-fin:igReportPrint():MainThread:427784s: --------------------------------------------------------------
I4494HOS-1code\engine\shared\core\common\report\igReportHandler.cpp:L147:game-nx-fin:igReportPrint():MainThread:427784s: LOADING LEVEL: 'Octane/Octane_StartScreen/Octane_StartScreen'
I4494HOS-1code\engine\shared\core\common\report\igReportHandler.cpp:L147:game-nx-fin:igReportPrint():MainThread:427784s: --------------------------------------------------------------
I11250HOS-1code\engine\shared\core\common\report\igReportHandler.cpp:L147:game-nx-fin:igReportPrint():MainThread:427791s: ------------- level finished loading in 6.76 secs (10.22)-------------
E16939HOS-43SignalHandler: Thread #43 has crashed due to signal: Segmentation fault
Stack Trace:
* 0x805AEE600 (nn::audio::AppendWaveBuffer(nn::audio::VoiceType*, nn::audio::WaveBuffer const*) from sdk.nso)
* 0x800FCA170 (FMOD::OutputNnAudioRenderer::updateOutput() from main.nso)
* 0x801056660 (FMOD::Thread::callback(void*) from main.nso)
* 0x805D86BD8 (from sdk.nso)
* 0x805D8B038 (from sdk.nso)
* 0x805D8AFC0 (from sdk.nso)
CPU Context:
  Fault Address: 0x3591FCF18
  Stack Pointer: 0x198FC4EEE0
  X0 : 0x1                X1 : 0x189EC1C9F0
  X2 : 0x0                X3 : 0x800
  X4 : 0x0                X5 : 0x20B
  X6 : 0x1                X7 : 0x198FC4ECE8
  X8 : 0x189EC15070       X9 : 0x1594CED028
  X10: 0x3591FCE78        X11: 0x189EC1A000
  X12: 0x189EC1D320       X13: 0x0
  X14: 0x0                X15: 0x0
  X16: 0x804941670        X17: 0x805AEE590
  X18: 0x0                X19: 0x189EC1C9F0
  X20: 0x189EC0B648       X21: 0x189EC0B668
  X22: 0x189EC1C9F0       X23: 0x0
  X24: 0x0                X25: 0x0
  X26: 0x0                X27: 0x0
  X28: 0x0                X29: 0x198FC4EEF0
  X30: 0x800FCA170        X31: 0x198FC4EEE0
W16939HOS-43Kill: Killing HOS-0 in KProcess
W16940EmuMainKill: Killing and joining all threads in KProcess with new thread creation disabled
W16947HOS-2RemoveThread: T2 was not in C2's queue
W16949HOS-3RemoveThread: T3 was not in C2's queue
W16952HOS-4RemoveThread: T4 was not in C0's queue
W16954HOS-5RemoveThread: T5 was not in C2's queue
W16958HOS-6RemoveThread: T6 was not in C2's queue
W16961HOS-17RemoveThread: T17 was not in C2's queue
W16964HOS-18RemoveThread: T18 was not in C0's queue
W16968HOS-20RemoveThread: T20 was not in C2's queue
W16971HOS-21RemoveThread: T21 was not in C0's queue
W16974HOS-32RemoveThread: T32 was not in C0's queue
W16976HOS-33RemoveThread: T33 was not in C2's queue
W16978HOS-34RemoveThread: T34 was not in C2's queue
W16980HOS-35RemoveThread: T35 was not in C1's queue
W16981HOS-36RemoveThread: T36 was not in C2's queue
W16983HOS-37RemoveThread: T37 was not in C0's queue
W16984HOS-38RemoveThread: T38 was not in C1's queue
W16986HOS-39RemoveThread: T39 was not in C2's queue
W16988HOS-41RemoveThread: T41 was not in C1's queue
W16989HOS-42RemoveThread: T42 was not in C1's queue
W16992HOS-45RemoveThread: T45 was not in C1's queue
W16995HOS-46RemoveThread: T46 was not in C1's queue
W16997HOS-47RemoveThread: T47 was not in C1's queue
W17000HOS-48RemoveThread: T48 was not in C1's queue
W17004HOS-49RemoveThread: T49 was not in C1's queue
W17007HOS-51RemoveThread: T51 was not in C2's queue

**Comment by MuhSlam** [comment] 2023-03-12 12:28
Duplicate of #1184
Use search function next time

**Comment by Yusefsar** [comment] 2023-03-12 12:33
I have seen it but it doesn't had any fix . So no luck I guess

**Comment by Yusefsar** [comment] 2023-03-12 12:46
Update: disabling audio caused the game to run consistent but freeze after Activision screen

**Comment by EZonTheEyes** [comment] 2023-03-12 14:56
Duplicate of #1184 please submit updated info as a comment to there

**Closed by EZonTheEyes** 2023-03-12 14:56 UTC

**Comment by toastmaloast** [comment] 2023-04-24 20:27
This game works perfectly fine for me
I'm using a Samsung Galaxy s23 (non plus or ultra) 
Snapdragon 8 Gen2
