### ISSUE TITLE
Super Mario Maker 2

### ISSUE THREAD

**Issue by SinUsername** [skyline-emu/skyline-games-list#654] opened 2022-06-14 14:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1200

### Android Version

10

### SoC type

Kirin

### Device GSMArena link

https://m.gsmarena.com/huawei_p30_lite-9545.php

### Game Behaviour

After a long time the game was already left on the black screen. That good but it is not yet in anything
![Screenshot_20220614_093630_skyline emu](https://user-images.githubusercontent.com/94080806/173605408-403a7fd7-b0e9-45d7-befc-d29708361846.jpg)

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[emulation.txt](https://github.com/skyline-emu/skyline-games-list/files/8900764/emulation.txt)

**Comment by Crytonics** [comment] 2022-06-14 14:43
Duplicate of #261

**Closed** 2022-06-14 14:43 UTC
