### ISSUE TITLE
BOXBOY! + BOXGIRL! 

### ISSUE THREAD

**Issue by Theus061** [skyline-emu/skyline-games-list#978] opened 2022-08-19 13:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

#1310

### Android Version

11

### SoC type

Snapdragon

### Device GSMArena link

https://www.google.com/amp/s/m.gsmarena.com/oneplus_7_pro-ampp-9689.php

### Game Behaviour

Playable with random graphic glitches, audio is perfect.
![Screenshot_20220819-101522_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/108691734/185631306-6a4f99e7-11fa-4f8c-981b-3d5ab4cebfe5.jpg)
![Screenshot_20220819-101650_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/108691734/185631337-1f060a19-2526-4c96-9bb7-470e5ef68ff5.jpg)

https://user-images.githubusercontent.com/108691734/185631507-aeeb5b04-ce85-4da9-b821-839bbef8c003.mp4

### Is Log Level is set to 'Info'?

- [X] Yes

### Log file

[boxboyboxgirl.txt](https://github.com/skyline-emu/skyline-games-list/files/9382625/boxboyboxgirl.txt)

```
W1135HOS-0HandleRequest: Cannot find function in service 'visrv::IApplicationDisplayService': 0x836 (2102)
```

**Comment by rna0** [comment] 2022-09-02 10:33
there already is an issue for this, see #105

**Comment by Crytonics** [comment] 2022-09-02 14:15
Duplicate of #105

**Closed by Crytonics** 2022-09-02 14:15 UTC
Labels: status-playable, gpu, services
